### ISSUE TITLE
Suport for crossterm 0.26

### ISSUE THREAD

**Issue by ColorMaestro** [rhysd/tui-textarea#10]
Hello,

crossterm latest verion is 0.26 since last week, could you pleas add support for it ?

Thanks

**Comment by lemon-sh** [comment]
why did you close this?

**Comment by ColorMaestro** [comment]
Well, in fact, I used this library for my school project and bumped into same problem as described in https://github.com/rhysd/tui-textarea/issues/9 :D thus realized it has been already spotted.
