### ISSUE TITLE
Change cursor shape

### ISSUE THREAD

**Issue by brooksvb** [rhysd/tui-textarea#11]
I've been trying to change the cursor style to a blinking bar for an editor program, but it seems like there isn't a way to do this beyond changing cursor color and [blink rate](https://docs.rs/tui/0.19.0/tui/style/struct.Modifier.html#associatedconstant.SLOW_BLINK).

I've tried doing so through [crossterm](https://docs.rs/crossterm/latest/crossterm/cursor/enum.SetCursorStyle.html#variant.BlinkingBar) but it seems like this is ignored in the rendering of the textarea.

```rust
//main.rs
...
use crossterm::cursor::SetCursorStyle;
use crossterm::event::{DisableMouseCapture, EnableMouseCapture};
use crossterm::terminal::{
    disable_raw_mode, enable_raw_mode, is_raw_mode_enabled, EnterAlternateScreen,
    LeaveAlternateScreen,
};
...
    crossterm::execute!(term.backend_mut(), SetCursorStyle::SteadyBar).unwrap();

    // Main render loop
    let mutex = Mutex::new(());
    while running.load(Ordering::SeqCst) {
        term.draw(|f| {
            let buffer = buffer.lock().unwrap();
            let buffer_widget = buffer.textarea.widget();
            let rectangle = Rect::new(0, 0, f.size().width, f.size().height);
            f.render_widget(buffer_widget, rectangle);
        })
        .unwrap();

        // TUI refresh rate
        let guard = mutex.lock().unwrap();
        _ = condvar.wait_timeout(guard, Duration::from_millis(50));
    }
...
```

And my implementation of `Buffer` which creates the `TextArea`
``` rust
...
impl Buffer {
    pub fn new(config: &Config) -> io::Result<Self> {
        // TODO: Generate path
        let path = config.output_name.clone();

        let file_already_existed = path.exists();
        let mut textarea = if let Ok(md) = path.metadata() {
            if md.is_file() {
                let contents = fs::read_to_string(path.clone())?;
                TextArea::from(contents.lines())
            } else {
                // Path exists but is not a file
                return Err(io::Error::new(
                    io::ErrorKind::Other,
                    format!("{:?} exists but is not a file", path),
                ));
            }
        } else {
            TextArea::default() // File does not exist
        };
        textarea.set_hard_tab_indent(config.use_hard_indent);
        // Remove default underline style from active line
        textarea.set_cursor_line_style(Style::default());
        Ok(Self {
            textarea,
            path,
            modified: false,
            file_already_existed,
        })
    }
    ...
```

I've tried calling `textarea.set_cursor_style` from here (https://docs.rs/tui-textarea/latest/tui_textarea/struct.TextArea.html#method.set_cursor_style), but the [`Style` struct](https://docs.rs/tui/0.19.0/tui/style/struct.Style.html) from the `tui` crate just doesn't seem to support a way to change the cursor shape.

Is this a limitation of the `tui` crate? Is there a way I can change my cursor shape?

**Comment by rhysd** [comment]
Looks duplicate of #7. Do you have any points to discuss which are not done in #7?

**Comment by brooksvb** [comment]
It is a duplicate. My apologies for not seeing the issue.

If I understand correctly, the cursor shown in a textarea is sort of a "virtual cursor," and not controlled/rendered by the terminal, which is why my `crossterm` method did not work.
