### ISSUE TITLE
New minor version for ratatui dependencies

### ISSUE THREAD

**Issue by AmmarAbouZor** [rhysd/tui-textarea#18]
Hi, at first I want to thank you on this great library. I used it in my app [tui-journal](https://github.com/ammarabouzor/tui-journal) and it was a charm!

I came across an issue while trying updating my app to use [ratatui](https://github.com/tui-rs-revival/ratatui) instead of tui-rs.

The problem is that cargo didn't recognize the new features for ratatui since they are in save version as before, and it seems that cargo cache this info somewhere in my machine. I've tried to clear my caches but this didn't solve the problem.

I believe the version should be updated to 0.2.1 since there are new features has been added.

Here is the error message I got when I try to add the features with cargo cli

```bash
$ cargo add tui-textarea --no-default-features -F ratatui-crossterm

    Updating crates.io index
      Adding tui-textarea v0.2.0 to dependencies.
error: unrecognized feature for crate tui-textarea: ratatui-crossterm
disabled features:
    arbitrary, crossterm, search, termion

```

And here is the error message when I try to add inside cargo.toml

```toml
[dependencies]
crossterm = "0.26.1"
ratatui = "*"
tui-textarea = { version = "*", features = ["ratatui-crossterm"], default-features=false }
```
```bash
error: failed to select a version for `tui-textarea`.
versions that meet the requirements `*` (locked to 0.2.0) are: 0.2.0

the package `test_ratatui` depends on `tui-textarea`, with features: `ratatui-crossterm` but `tui-textarea` does not have these features.

failed to select a version for `tui-textarea` which could resolve this conflict
```

**Comment by AmmarAbouZor** [comment]
@rhysd Would it be helpful if I make a PR for it?

**Comment by haydenflinner** [comment]
This solved it for me:
```toml
tui-textarea = { git = "https://github.com/rhysd/tui-textarea", features = ["ratatui-crossterm"], default-features=false }
```

**Comment by AmmarAbouZor** [comment]
@haydenflinner This solution will work as long as your app isn't published on `crates.io` itself, because `crates.io` doesn't allow having dependencies in your app which source isn't crates.io like git or local dependencies.

That's why this update is a must for all apps that's published on `crates.io`  @rhysd

**Comment by AmmarAbouZor** [comment]
@danielo515 
Yes it should be enough to increase the version here (patch or minor) and then publish it to `crates.io`

Hopefully we'll hear soon from @rhysd  :pray:

**Comment by TheAwiteb** [comment]
You can use [ratatui-textarea](https://github.com/TheAwiteb/ratatui-textarea) a fully supported `tui-textarea` for ratatui

**Comment by AmmarAbouZor** [comment]
The new release of text-area here and on `crates.io` solved this issue. 
Thanks @rhysd :heart:
