### ISSUE TITLE
Doesn't work with ratatui 0.24

### ISSUE THREAD

**Issue by TheKnarf** [rhysd/tui-textarea#36]
`ratatui_minimal` doesn't work with `ratatui` 0.24.0

**Comment by joshka** [comment]
I was able to run `cargo run --example minimal` fine on macOS with tui-textarea's cargo.toml set to 0.24.0 - can you provide more details on the error please (I'm not sure if the more recent changes @rhysd made today have fixed this since then).

**Comment by rhysd** [comment]
@joshka This issue had been created before I pushed https://github.com/rhysd/tui-textarea/commit/a0aade4800944eb8df8b71af2ccfea2d7c90d6d6. The commit fixed this issue.
