### ISSUE TITLE
Feature request: prompt for single line TextArea

### ISSUE THREAD

**Issue by tranzystorek-io** [rhysd/tui-textarea#38]
I'd like to create a fuzzy finder UI similar to `fzf`, with a `> ` prompt showing that the user can type the match phrase there, instead of surrounding the input area with a block.

What is missing in `TextArea` is some kind of way or mode to add such a prompt on the left of a line.

I'm aware this is stretching the already wide number of uses for `TextArea`, and that it clashes a bit with the already existing, more editor-oriented API like line numbers, but `tui-textarea` seems to be the best-tailored solution otherwise.

**Comment by pm100** [comment]
I think this is already doable. You can get a naked input box with no border by constucting using new instead of default. This has block set to none, only the raw input area is drawn. To get the prompt simply draw the > one char to the left of the texarea

**Comment by rhysd** [comment]
I agree with @pm100. You can combine `Text` widget and textarea widget in a single `Block` widget with horizontal layout.

- `Block` (horizontal layout)
  - `Text` (for prompt)
  - textarea (for input)

**Comment by tranzystorek-io** [comment]
Thanks, I used this suggestion and it worked perfect! You probably meant `Paragraph` instead of `Text` as a tiny nitpick for anyone reading this in the future 😄
