### ISSUE TITLE
hard tab now adds extra padding character on display

### ISSUE THREAD

**Issue by pm100** [rhysd/tui-textarea#43]
on current head

run minimal sample with hard tab set on (I set width to 10),

enter a\tb\na\b

display is

![image](https://github.com/rhysd/tui-textarea/assets/489231/0ebfc5f0-a640-4f94-a4e6-e3de583249f5)

now cursor left into the gap

![image](https://github.com/rhysd/tui-textarea/assets/489231/8a3dcd90-85d8-40bc-b58d-fb8077ae5408)

the tab space grew by one character

I have tried an initial debug but its not obvious

**Comment by rhysd** [comment]
Thank you for reporting. This is a bug. I could reproduce it.

**Comment by pm100** [comment]
Did you see my question about hard tabs ? In the insert_str closed issue

**Comment by rhysd** [comment]
@pm100 I haven't seen it. I'll check.

I confirmed the root cause of this issue and now fixing it with refactoring highlight.rs.

**Comment by rhysd** [comment]
I confirmed the fix:

![tmp](https://github.com/rhysd/tui-textarea/assets/823277/bc84409e-82d2-4c18-a2ce-673967daf6ed)
