### ISSUE TITLE
remove the <'a> requirement on TextArea

### ISSUE THREAD

**Issue by pm100** [rhysd/tui-textarea#46]
Dropping TTA into an existing project can be very disruptive since it requires lifetime annotation. This can ripple up through an app. This makes it a barrier to adoption by other projects (speaking from experience here)

The solution would be to have a private Block equivalent that owns the title string (s) rather than using references.

**Comment by rhysd** [comment]
The lifetime parameter is used for ratatui's `Block` instance so it cannot be removed.

**Comment by pm100** [comment]
I know, hence the different block in my pr

**Comment by rhysd** [comment]
I saw your PR changes a bit. Do you mean adding new API which is very similar to `Block` only for removing the lifetime parameter? I don't think it is a good tradeoff. We should use ratatui's API as much as possible to make our API as minimal as possible. If we add new widget, users need to learn about it. I feel the cost is much bigger than just handling small one lifetime parameter.

If you want to hide the parameter and you're not benefit from it, you can do:

```rust
type TextArea = TextArea<'static>;
```

**Comment by pm100** [comment]
I tried multiple things to avoid propagating the 'a over several weeks , and yet I never tried that one :-). I know it comes with some restrictions, I need to check if it will work in gitui.

**Comment by rhysd** [comment]
Great. Thanks for your confirmation.

**Comment by joshka** [comment]
Ha - I almost mentioned the same solution in the Ratatui side of this :D

**Comment by holly-hacker** [comment]
Could this be documented somewhere? I just spent 15 minutes adding and removing lifetimes everywhere and was about to open a duplicate of this issue. Using a `'static` lifetime is a fine workaround but it's something you need to be aware off first.
