### ISSUE TITLE
Allow input widgets to appear wherever the are in a terminal session

### ISSUE THREAD

**Issue by garyrob** [rhysd/tui-textarea#58]
In your demos, the input widgets clear the screen and appear at the top. But for many applications, it's better to be able to show the terminal session up to the point where the input occurs, and have the input area on the next line.

I'm not sure whether there's some way to accomplish that already with tui-textarea, or whether this is a feature request. If there's a way to do it I suggest adding it to your examples!

**Comment by joshka** [comment]
This is a feature of Ratatui itself. Configure a terminal with an Inline or fixed viewport and don't enter the alternate screen. Check the inline and ratatui-logo examples for a demonstration of how to achieve this.

**Comment by garyrob** [comment]
OK, thank you for answering such a basic question. I'll go check out ratatui!
