### ISSUE TITLE
Selecting text

### ISSUE THREAD

**Issue by wichops** [rhysd/tui-textarea#6]
👋🏽 I have very little experience with Rust and working with Terminal UI. 

Is there a recommended way of selecting tui-textarea text with either mouse or keyboard?
For example moving the cursor with `S+Right` to move the cursor and select the text below the cursor range at the same time?

**Comment by pm100** [comment]
selecting with a mouse depends on the caller of textarea and the platform. A project I use textarea in does not turn on mouse event capture. THis means that the platform mouse behaviour works, that may or may not allow copy to clipboard. The samples in textarea turn on mouse capture, that means that the mouse events dont get handled by the platform. The only mouse event that textarea supports in scroll up and down.

Try editing the minimal sample and change 

`   crossterm::execute!(stdout, EnterAlternateScreen, EnableMouseCapture)?;`

to

`   crossterm::execute!(stdout, EnterAlternateScreen)?;`

As regards to keyboard select that does not exist. I assume that if it did you would want copy and cut / delete to work. @rhysd I am working on that at the moment. I think its a useful feature

**Comment by pm100** [comment]
pr is #39

**Comment by pm100** [comment]
@rhysd - could you accept this PR sooner rather than later. I want to submit a new PR to gitui (minus the 'a nonsense - ty) and having this feature as bonus would be a great incentive to them

**Comment by rhysd** [comment]
Since this PR is large, it will take a bit longer time.
