### ISSUE TITLE
Update to ratatui 0.26

### ISSUE THREAD

**Issue by holly-hacker** [rhysd/tui-textarea#60]
Hi, tui-textarea currently targets ratatui 0.24.0, but the latest version is 0.26.1. Could you update the dependency and publish a new release?

**Comment by joshka** [comment]
Tui-textarea's >=0.23 version spec means you only have to run cargo update and you'll be using the latest version released. (0.26.2 at time of writing). This is actually bad behavior as it causes the problems mentioned in:
- https://doc.rust-lang.org/cargo/reference/resolver.html#unexpected-dependency-duplication
- https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#multiple-version-requirements

**Comment by rhysd** [comment]
This issue was solved by #69.
