### ISSUE TITLE
Feature request: Changing cursor shape

### ISSUE THREAD

**Issue by JayJaySea** [rhysd/tui-textarea#7]
First let me tell, this crate is amazing!
It completely suits me as it is for now, but in the future it might be helpful to be able to change cursor shape (i want to make a vim-like text area in my project at some point, and changing cursor shape between normal mode (block) and insert mode (line) would make it way more user friendly)

Thanks again for making this crate!

**Comment by rhysd** [comment]
This library renders a cursor by changing the color of cell. So I think changing cursor is not possible.

**Comment by JayJaySea** [comment]
No worries then, my project will be good with emacs-like text area as well ;) Thought it would be an easy fix when asked, but it seems to be not worth the trouble in the end.

Thanks for quick reply!
