### ISSUE TITLE
`WordEnd` member for `CursorMove` enum

### ISSUE THREAD

**Issue by achristmascarl** [rhysd/tui-textarea#74]
A minor thing I noticed was missing while implementing vim emulation based on the [example](https://github.com/rhysd/tui-textarea/blob/main/examples/vim.rs) was going to the next "end of word" via 'e' was missing, and that there's no corresponding enum member in `CursorMove`

I'd propose adding a new `WordEnd` member to the enum and handle it using the existing `find_word_end_forward()` method

**Comment by rhysd** [comment]
Closing as #75 was merged.
