### ISSUE TITLE
In Vim example delete up to WordEnd doesn't delete last word character

### ISSUE THREAD

**Issue by fmorroni** [rhysd/tui-textarea#76]
What the title says. I modified the code like this to fix the issue:
```rs
Input {
    key: Key::Char('e'),
    ctrl: false,
    ..
} => {
    self.textarea.move_cursor(CursorMove::WordEnd);
    if self.mode == Mode::Operator('d') {
        self.textarea.move_cursor(CursorMove::Forward);
    }
}
```
Which isn't very pretty but it works.

**Comment by rhysd** [comment]
Thanks it is a bug of the example. `WordEnd` works fine but Vim's `e` mapping behaves differently from `e` in normal mode and the `vim` example does not emulate it well.
