### ISSUE TITLE
Why doesn't `TextArea` implement `Widget` trait

### ISSUE THREAD

**Issue by fmorroni** [rhysd/tui-textarea#78]
Hi, why doesn't `TextArea` implement the `Widget` trait? I know we have the `widget()` method but that seems kind of unnecessary to me. Is there an advantage to having it that way?

**Comment by rhysd** [comment]
because `Widget::render` requires to move out `self`

**Comment by rhysd** [comment]
I noticed that `&TextArea` can implement `Widget`. It might be smarter.

```rust
impl<'a> Widget for &'a TextArea<'a> {
    // ...
}

// Usage
term.draw(|f| {
    f.render_widget(&textarea, f.size());
})?;
```

**Comment by fmorroni** [comment]
> I noticed that `&TextArea` can implement `Widget`. It might be smarter.
> 
> ```rust
> impl<'a> Widget for &'a TextArea<'a> {
>     // ...
> }
> 
> // Usage
> term.draw(|f| {
>     f.render_widget(&textarea, f.size());
> })?;
> ```

Yeah that's basically what I did for a vim input widget I'm making. Seems to work fine.

**Comment by rhysd** [comment]
@fmorroni Thanks for clarification. I'll consider this.

**Comment by rhysd** [comment]
This was included in [v0.5.3 release](https://github.com/rhysd/tui-textarea/releases/tag/v0.5.3).

**Comment by fmorroni** [comment]
> This was included in [v0.5.3 release](https://github.com/rhysd/tui-textarea/releases/tag/v0.5.3).

Great thanks!

**Comment by evbo** [comment]
@rhysd did this break again recently?:

```rust
error[E0277]: the trait bound `&tui_textarea::textarea::TextArea<'_>: Widget` is not satisfied
  --> src/main.rs:72:30
   |
72 |         frame.render_widget(&self.state.text_area, area);
   |               -------------  ^^^^^^^^^^^^^^^^^^^^ the trait `widgets::WidgetRef` is not implemented for `&tui_textarea::textarea::TextArea<'_>`, which is required by `&tui_textarea::textarea::TextArea<'_>: Widget`
   |               |
   |               required by a bound introduced by this call
```

**Comment by rhysd** [comment]
@evbo This issue is already closed. Could you create new one?
